title:              Carlos Maldonado
email:              carlos.maldonado7@gmail.com
description:        ¡Bienvenid@ a mi Portafolio!
author:             Start Bootstrap
baseurl:            ""
linkedin_username: "https://www.linkedin.com/in/carlos17/"
url:                "https://Carlos-maldonado578.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
